#!/bin/bash
# Setup script for OpenMemory API test environment
# This script ensures the database and server are properly configured for testing

set -e  # Exit on error

echo "🔧 OpenMemory Test Environment Setup"
echo "===================================="
echo ""

# Navigate to backend directory
cd "$(dirname "$0")/.."

# Step 1: Run migrations
echo "📦 Step 1: Running database migrations..."
npm run migrate
echo "✅ Migrations complete"
echo ""

# Step 2: Check .env configuration
echo "⚙️  Step 2: Checking environment configuration..."

ENV_FILE=".env"
if [ ! -f "$ENV_FILE" ]; then
    echo "⚠️  No .env file found. Creating recommended test configuration..."
    cat > "$ENV_FILE" << 'EOF'
# OpenMemory Test Configuration
# Generated by setup-test-env.sh

# Disable proxy-only mode (required for API tests)
OM_PROXY_ONLY_MODE=false

# Use synthetic embeddings (no API keys required)
OM_EMBEDDINGS=synthetic
OM_TIER=fast

# Optional: Set API key for authentication testing
# OM_API_KEY=test-api-key-12345

# Database configuration
OM_METADATA_BACKEND=sqlite
OM_DB_PATH=./data/openmemory.sqlite

# Vector storage
OM_VECTOR_STORAGE=sqlite
# OM_VECTOR_STORAGE=qdrant

# Server configuration
PORT=3695
EOF
    echo "✅ Created .env file with recommended test settings"
else
    echo "ℹ️  .env file exists. Checking configuration..."
    
    # Check critical settings
    if grep -q "OM_PROXY_ONLY_MODE=true" "$ENV_FILE"; then
        echo "⚠️  WARNING: OM_PROXY_ONLY_MODE is set to true"
        echo "   Tests will fail. Please set to false or comment out."
    fi
    
    if ! grep -q "OM_EMBEDDINGS" "$ENV_FILE"; then
        echo "⚠️  WARNING: OM_EMBEDDINGS not set"
        echo "   Recommend adding: OM_EMBEDDINGS=synthetic"
    fi
    
    if ! grep -q "OM_TIER" "$ENV_FILE"; then
        echo "⚠️  WARNING: OM_TIER not set"
        echo "   Recommend adding: OM_TIER=fast"
    fi
fi
echo ""

# Step 3: Display test instructions
echo "📋 Step 3: Ready to run tests!"
echo ""
echo "To start the server:"
echo "  npm run dev"
echo ""
echo "In another terminal, run tests:"
echo "  npm test"
echo ""
echo "Or use one-liner with test configuration:"
echo "  OM_EMBEDDINGS=synthetic OM_TIER=fast npm run dev"
echo ""

# Step 4: Offer to start server
echo "Would you like to start the server now? (y/n)"
read -r response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
    echo ""
    echo "🚀 Starting server with test configuration..."
    OM_PROXY_ONLY_MODE=false OM_EMBEDDINGS=synthetic OM_TIER=fast npm run dev
else
    echo ""
    echo "✅ Setup complete! Run 'npm run dev' when ready."
fi
